name: s86_0126_flutter_basics
description: A new Flutter project.

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  cloud_functions: ^5.0.0
  firebase_messaging: ^15.0.0
  image_picker: ^1.0.0
flutter:
  assets:
    - assets/images/
    - assets/icons/